CREATE DATABASE doingdone
CHARACTER SET UTF8
COLLATE UTF8_GENERAL_CI;
USE doingdone;
CREATE TABLE task (
	id TINYINT NOT NULL AUTO_INCREMENT,
	create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
	status TINYINT(1),
	name VARCHAR(500) NOT NULL,
	file_link TEXT DEFAULT NULL,
	expiration_time DATETIME DEFAULT NULL,
	project_id TINYINT NOT NULL,
	user_id TINYINT NOT NULL,
	PRIMARY KEY (id),
	INDEX (name)
);

CREATE TABLE project (
	id TINYINT NOT NULL AUTO_INCREMENT,
	name VARCHAR(500) NOT NULL,
	user_id TINYINT NOT NULL,
	PRIMARY KEY (id),
	UNIQUE (name)
);

CREATE TABLE user (
	id TINYINT(4) NOT NULL AUTO_INCREMENT,
	create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
	email VARCHAR(254) NOT NULL,
	name VARCHAR(500) NOT NULL,
	password VARCHAR(500) NOT NULL,
	PRIMARY KEY (id),
	UNIQUE (email)
);
